### ISSUE TITLE
BUG: ProvisionedThroughputExceededException with Kinesis

### ISSUE THREAD

**Issue by Binjaaa** [lumigo-io/lumigo-CLI#25]
I started listening for new Kinesis events after 4-5 I experienced the following exception: 
```
ProvisionedThroughputExceededException: Rate exceeded for shard shardId-...
    at Request.extractError (/usr/local/lib/node_modules/lumigo-cli/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.callListeners (/usr/local/lib/node_modules/lumigo-cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/lumigo-cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/lumigo-cli/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/local/lib/node_modules/lumigo-cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/lumigo-cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/lumigo-cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/lumigo-cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/lumigo-cli/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/usr/local/lib/node_modules/lumigo-cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)```

**Comment by Binjaaa** [comment]
Not sure it's that helpful but it might be:

```If a PutRecord request cannot be processed because of insufficient provisioned throughput on the shard involved in the request, PutRecord throws ProvisionedThroughputExceededException.```

I have only 1 shard at the moment.

**Comment by theburningmonk** [comment]
We're not doing any put, but it could be related to the reads we're doing. Do you have one or more Lambda function subscribed to the stream already?

**Comment by Binjaaa** [comment]
Yes, 50+ of Lambda functions.

**Comment by theburningmonk** [comment]
Right, that in itself is gonna be a problem! All those functions are gonna be reading from the stream 5 times a sec, and you only get 5 reads/s per shard (see more details [here](https://lumigo.io/blog/lambda-and-kinesis-beware-of-hot-streams/))

The functions are gonna see a lot of throttling as well, but you don't tend to see those throttling exceptions because AWS retries for you.

**Comment by theburningmonk** [comment]
@Binjaaa I added more robust retries so hopefully, you're less likely to see this error
