### ISSUE TITLE
analyze-lambda-cold-starts fails if log group not found

### ISSUE THREAD

**Issue by dobeerman7** [lumigo-io/lumigo-CLI#79]
```sh
$ luci analyze-lambda-cold-starts -r eu-central-1
analyzing cold starts over the last 60 minutes
eu-central-1: running CloudWatch Insights query against 211 log groups
eu-central-1: query start time is 2020-03-20T07:58:54.864Z
eu-central-1: end time is 2020-03-20T08:58:54.864Z
ResourceNotFoundException: Log group '/aws/lambda/serverlessrepo-lumigo-cli-powertuning-la-optimizer-VE67B9KTVZYZ' does not exist for account ID 'xxxxxxxxxxxx' (Service: AWSLogs; Status Code: 400; Error Code: ResourceNotFoundException; Request ID: 721a9480-2c08-4d2a-add7-08782caa7e73)
    at Request.extractError (/usr/local/lib/node_modules/lumigo-cli/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.callListeners (/usr/local/lib/node_modules/lumigo-cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (/usr/local/lib/node_modules/lumigo-cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (/usr/local/lib/node_modules/lumigo-cli/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (/usr/local/lib/node_modules/lumigo-cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (/usr/local/lib/node_modules/lumigo-cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at /usr/local/lib/node_modules/lumigo-cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (/usr/local/lib/node_modules/lumigo-cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (/usr/local/lib/node_modules/lumigo-cli/node_modules/aws-sdk/lib/request.js:685:12)
    at Request.callListeners (/usr/local/lib/node_modules/lumigo-cli/node_modules/aws-sdk/lib/sequential_executor.js:116:18)

```

Is it possible to just print out the problem without interrupting the process?

**Comment by theburningmonk** [comment]
@dobeerman7 good shout 👍
