### ISSUE TITLE
TooManyRequestsException: Rate exceeded

### ISSUE THREAD

**Issue by imewish** [lumigo-io/lumigo-CLI#87]
I'm getting this issue.

with `lumigo-cli analyze-lambda-cold-starts -r us-east-1 -h 7`

```us-east-1: query returned 14 rows in total
us-east-1: analyzing Provisioned Concurrency for 2058 functions
TooManyRequestsException: Rate exceeded
    at Object.extractError (~/.nvm/versions/node/v12.16.1/lib/node_modules/lumigo-cli/node_modules/aws-sdk/lib/protocol/json.js:51:27)
    at Request.extractError (~/.nvm/versions/node/v12.16.1/lib/node_modules/lumigo-cli/node_modules/aws-sdk/lib/protocol/rest_json.js:55:8)
    at Request.callListeners (~/.nvm/versions/node/v12.16.1/lib/node_modules/lumigo-cli/node_modules/aws-sdk/lib/sequential_executor.js:106:20)
    at Request.emit (~/.nvm/versions/node/v12.16.1/lib/node_modules/lumigo-cli/node_modules/aws-sdk/lib/sequential_executor.js:78:10)
    at Request.emit (~/.nvm/versions/node/v12.16.1/lib/node_modules/lumigo-cli/node_modules/aws-sdk/lib/request.js:683:14)
    at Request.transition (~/.nvm/versions/node/v12.16.1/lib/node_modules/lumigo-cli/node_modules/aws-sdk/lib/request.js:22:10)
    at AcceptorStateMachine.runTo (~/.nvm/versions/node/v12.16.1/lib/node_modules/lumigo-cli/node_modules/aws-sdk/lib/state_machine.js:14:12)
    at ~/.nvm/versions/node/v12.16.1/lib/node_modules/lumigo-cli/node_modules/aws-sdk/lib/state_machine.js:26:10
    at Request.<anonymous> (~/.nvm/versions/node/v12.16.1/lib/node_modules/lumigo-cli/node_modules/aws-sdk/lib/request.js:38:9)
    at Request.<anonymous> (~/.nvm/versions/node/v12.16.1/lib/node_modules/lumigo-cli/node_modules/aws-sdk/lib/request.js:685:12)```

Any help will be appreciated. Thanks

**Comment by theburningmonk** [comment]
wow, 2058 functions.. that's quite a lot!
